SKU_CATALOG = [
    {
        "sku_id": "S01",
        "name": "Arctic Balance Hybrid",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king", "cal_king"],
        "price": 1499,
        "firmness": 6,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Hybrid with gel memory foam and pocketed coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S02",
        "name": "Polar Motion Elite",
        "available_sizes": ["twin_xl", "full", "queen", "king", "cal_king"],
        "price": 1479,
        "firmness": 6,
        "support": 8,
        "cooling": 9,
        "motion_isolation": 9,
        "materials": "Cooling foam layers with zoned coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S03",
        "name": "Cloud Harbor Medium",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 1399,
        "firmness": 6,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 7,
        "materials": "Memory foam comfort over responsive coil base",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 120,
        "warranty_years": 12,
    },
    {
        "sku_id": "S04",
        "name": "Night Drift Hybrid",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king"],
        "price": 1299,
        "firmness": 5,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Breathable knit cover with foam and coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S05",
        "name": "Summit Chill Pro",
        "available_sizes": ["queen", "king", "cal_king"],
        "price": 1449,
        "firmness": 7,
        "support": 8,
        "cooling": 9,
        "motion_isolation": 8,
        "materials": "Phase-change cooling top over high-density foams",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S06",
        "name": "Metro Cool Comfort",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 1099,
        "firmness": 6,
        "support": 6,
        "cooling": 7,
        "motion_isolation": 7,
        "materials": "Foam and micro-coil hybrid construction",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 90,
        "warranty_years": 8,
    },
    {
        "sku_id": "S07",
        "name": "Serene Motion Max",
        "available_sizes": ["full", "queen", "king", "cal_king"],
        "price": 1490,
        "firmness": 6,
        "support": 7,
        "cooling": 7,
        "motion_isolation": 9,
        "materials": "Enhanced motion-control foam over pocketed coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S08",
        "name": "Everrest Breeze 8",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king", "cal_king"],
        "price": 1349,
        "firmness": 6,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Airflow channel foam and reinforced edge coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S09",
        "name": "Contour Quiet Hybrid",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 1249,
        "firmness": 6,
        "support": 7,
        "cooling": 7,
        "motion_isolation": 8,
        "materials": "Pressure-relief foam stack with zoned springs",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 110,
        "warranty_years": 10,
    },
    {
        "sku_id": "S10",
        "name": "AeroFlex Medium",
        "available_sizes": ["twin", "twin_xl", "full", "queen"],
        "price": 999,
        "firmness": 5,
        "support": 6,
        "cooling": 8,
        "motion_isolation": 7,
        "materials": "Breathable foam core with transition coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 90,
        "warranty_years": 8,
    },
    {
        "sku_id": "S11",
        "name": "Crescent Comfort Plus",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 1199,
        "firmness": 6,
        "support": 7,
        "cooling": 7,
        "motion_isolation": 7,
        "materials": "Balanced foam and coil layering",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S12",
        "name": "Pulse Support Hybrid",
        "available_sizes": ["twin_xl", "queen", "king", "cal_king"],
        "price": 1450,
        "firmness": 7,
        "support": 9,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Targeted lumbar support coils with cooling foams",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 12,
    },
    {
        "sku_id": "S13",
        "name": "Luma Chill Medium",
        "available_sizes": ["full", "queen", "king", "cal_king"],
        "price": 1380,
        "firmness": 6,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Cooling-gel foam quilt with adaptive coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S14",
        "name": "Urban Rest Core",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king"],
        "price": 950,
        "firmness": 6,
        "support": 6,
        "cooling": 6,
        "motion_isolation": 6,
        "materials": "Foam-forward hybrid with standard coil base",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 90,
        "warranty_years": 8,
    },
    {
        "sku_id": "S15",
        "name": "Zenith Cool Motion",
        "available_sizes": ["queen", "king", "cal_king"],
        "price": 1495,
        "firmness": 6,
        "support": 8,
        "cooling": 9,
        "motion_isolation": 8,
        "materials": "High-airflow cover with motion-control coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S16",
        "name": "CalmWave Hybrid",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 1325,
        "firmness": 5,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Contour foam layers over independently wrapped coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S17",
        "name": "ThermaQuiet 6",
        "available_sizes": ["twin_xl", "full", "queen", "king", "cal_king"],
        "price": 1435,
        "firmness": 6,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 9,
        "materials": "Thermal-regulating fabric and dense transition foam",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S18",
        "name": "Harbor Sleep Hybrid",
        "available_sizes": ["twin", "full", "queen", "king", "cal_king"],
        "price": 1275,
        "firmness": 6,
        "support": 7,
        "cooling": 7,
        "motion_isolation": 8,
        "materials": "Hybrid comfort stack with reinforced perimeter coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S19",
        "name": "BreezeForm Plus",
        "available_sizes": ["twin", "twin_xl", "full", "queen"],
        "price": 1125,
        "firmness": 6,
        "support": 6,
        "cooling": 8,
        "motion_isolation": 7,
        "materials": "Ventilated foam channels and responsive spring core",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 95,
        "warranty_years": 9,
    },
    {
        "sku_id": "S20",
        "name": "CoreFlex Entry",
        "available_sizes": ["twin", "full", "queen"],
        "price": 875,
        "firmness": 5,
        "support": 6,
        "cooling": 6,
        "motion_isolation": 6,
        "materials": "Entry foam hybrid with basic cooling cover",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 90,
        "warranty_years": 8,
    },
]
