CATALOG_FIXTURE_VERSION = "catalog_v2"


SKU_CATALOG = [
    {
        "sku_id": "S01",
        "name": "Arctic Balance Hybrid",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king", "cal_king"],
        "price": 1499,
        "firmness": 6,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Hybrid with gel memory foam and pocketed coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S02",
        "name": "Polar Motion Elite",
        "available_sizes": ["twin_xl", "full", "queen", "king", "cal_king"],
        "price": 1479,
        "firmness": 6,
        "support": 8,
        "cooling": 9,
        "motion_isolation": 9,
        "materials": "Cooling foam layers with zoned coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S03",
        "name": "Cloud Harbor Medium",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 1399,
        "firmness": 6,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 7,
        "materials": "Memory foam comfort over responsive coil base",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 120,
        "warranty_years": 12,
    },
    {
        "sku_id": "S04",
        "name": "Night Drift Hybrid",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king"],
        "price": 1299,
        "firmness": 5,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Breathable knit cover with foam and coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S05",
        "name": "Summit Chill Pro",
        "available_sizes": ["queen", "king", "cal_king"],
        "price": 1449,
        "firmness": 7,
        "support": 8,
        "cooling": 9,
        "motion_isolation": 8,
        "materials": "Phase-change cooling top over high-density foams",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S06",
        "name": "Metro Cool Comfort",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 1099,
        "firmness": 6,
        "support": 6,
        "cooling": 7,
        "motion_isolation": 7,
        "materials": "Foam and micro-coil hybrid construction",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 90,
        "warranty_years": 8,
    },
    {
        "sku_id": "S07",
        "name": "Serene Motion Max",
        "available_sizes": ["full", "queen", "king", "cal_king"],
        "price": 1490,
        "firmness": 6,
        "support": 7,
        "cooling": 7,
        "motion_isolation": 9,
        "materials": "Enhanced motion-control foam over pocketed coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S08",
        "name": "Everrest Breeze 8",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king", "cal_king"],
        "price": 1349,
        "firmness": 6,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Airflow channel foam and reinforced edge coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S09",
        "name": "Contour Quiet Hybrid",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 1249,
        "firmness": 6,
        "support": 7,
        "cooling": 7,
        "motion_isolation": 8,
        "materials": "Pressure-relief foam stack with zoned springs",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 110,
        "warranty_years": 10,
    },
    {
        "sku_id": "S10",
        "name": "AeroFlex Medium",
        "available_sizes": ["twin", "twin_xl", "full", "queen"],
        "price": 999,
        "firmness": 5,
        "support": 6,
        "cooling": 8,
        "motion_isolation": 7,
        "materials": "Breathable foam core with transition coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 90,
        "warranty_years": 8,
    },
    {
        "sku_id": "S11",
        "name": "Crescent Comfort Plus",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 1199,
        "firmness": 6,
        "support": 7,
        "cooling": 7,
        "motion_isolation": 7,
        "materials": "Balanced foam and coil layering",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S12",
        "name": "Pulse Support Hybrid",
        "available_sizes": ["twin_xl", "queen", "king", "cal_king"],
        "price": 1450,
        "firmness": 7,
        "support": 9,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Targeted lumbar support coils with cooling foams",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 12,
    },
    {
        "sku_id": "S13",
        "name": "Luma Chill Medium",
        "available_sizes": ["full", "queen", "king", "cal_king"],
        "price": 1380,
        "firmness": 6,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Cooling-gel foam quilt with adaptive coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S14",
        "name": "Urban Rest Core",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king"],
        "price": 950,
        "firmness": 6,
        "support": 6,
        "cooling": 6,
        "motion_isolation": 6,
        "materials": "Foam-forward hybrid with standard coil base",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 90,
        "warranty_years": 8,
    },
    {
        "sku_id": "S15",
        "name": "Zenith Cool Motion",
        "available_sizes": ["queen", "king", "cal_king"],
        "price": 1495,
        "firmness": 6,
        "support": 8,
        "cooling": 9,
        "motion_isolation": 8,
        "materials": "High-airflow cover with motion-control coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S16",
        "name": "CalmWave Hybrid",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 1325,
        "firmness": 5,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 8,
        "materials": "Contour foam layers over independently wrapped coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S17",
        "name": "ThermaQuiet 6",
        "available_sizes": ["twin_xl", "full", "queen", "king", "cal_king"],
        "price": 1435,
        "firmness": 6,
        "support": 7,
        "cooling": 8,
        "motion_isolation": 9,
        "materials": "Thermal-regulating fabric and dense transition foam",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S18",
        "name": "Harbor Sleep Hybrid",
        "available_sizes": ["twin", "full", "queen", "king", "cal_king"],
        "price": 1275,
        "firmness": 6,
        "support": 7,
        "cooling": 7,
        "motion_isolation": 8,
        "materials": "Hybrid comfort stack with reinforced perimeter coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S19",
        "name": "BreezeForm Plus",
        "available_sizes": ["twin", "twin_xl", "full", "queen"],
        "price": 1125,
        "firmness": 6,
        "support": 6,
        "cooling": 8,
        "motion_isolation": 7,
        "materials": "Ventilated foam channels and responsive spring core",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 95,
        "warranty_years": 9,
    },
    {
        "sku_id": "S20",
        "name": "CoreFlex Entry",
        "available_sizes": ["twin", "full", "queen"],
        "price": 875,
        "firmness": 5,
        "support": 6,
        "cooling": 6,
        "motion_isolation": 6,
        "materials": "Entry foam hybrid with basic cooling cover",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 90,
        "warranty_years": 8,
    },
    {
        "sku_id": "S21",
        "name": "Cedar Lane Essential",
        "available_sizes": ["twin", "full", "queen"],
        "price": 229,
        "firmness": 6,
        "support": 6,
        "cooling": 5,
        "motion_isolation": 7,
        "materials": "Quilted foam over a traditional innerspring unit",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 30,
        "warranty_years": 5,
    },
    {
        "sku_id": "S22",
        "name": "QuietNest Foam",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king"],
        "price": 279,
        "firmness": 5,
        "support": 5,
        "cooling": None,
        "motion_isolation": 9,
        "materials": "All-foam construction with a dense motion-control layer",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 45,
        "warranty_years": 5,
    },
    {
        "sku_id": "S23",
        "name": "Ridgeway Firm",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 329,
        "firmness": 8,
        "support": 8,
        "cooling": 5,
        "motion_isolation": None,
        "materials": "Firm support foam over tempered steel coils",
        "contains_latex": False,
        "haul_away_CA_available": None,
        "trial_days": 60,
        "warranty_years": 6,
    },
    {
        "sku_id": "S24",
        "name": "Willow Plush Comfort",
        "available_sizes": ["twin", "full", "queen"],
        "price": 349,
        "firmness": 4,
        "support": None,
        "cooling": 6,
        "motion_isolation": 8,
        "materials": "Plush memory foam with a flexible foam base",
        "contains_latex": None,
        "haul_away_CA_available": True,
        "trial_days": 60,
        "warranty_years": None,
    },
    {
        "sku_id": "S25",
        "name": "Parkside Coil Comfort",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king"],
        "price": 379,
        "firmness": 7,
        "support": 7,
        "cooling": 7,
        "motion_isolation": 4,
        "materials": "Open-coil innerspring with a breathable quilted top",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 30,
        "warranty_years": 5,
    },
    {
        "sku_id": "S26",
        "name": "Harborline Basic Hybrid",
        "available_sizes": ["full", "queen", "king"],
        "price": 399,
        "firmness": None,
        "support": 6,
        "cooling": 5,
        "motion_isolation": 7,
        "materials": "Comfort foam over individually wrapped entry-level coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": None,
        "warranty_years": 6,
    },
    {
        "sku_id": "S27",
        "name": "Stillwater Motion Foam",
        "available_sizes": ["twin", "full", "queen", "king", "cal_king"],
        "price": 449,
        "firmness": 5,
        "support": 6,
        "cooling": 5,
        "motion_isolation": 9,
        "materials": "Slow-response memory foam with a high-density base",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 75,
        "warranty_years": 8,
    },
    {
        "sku_id": "S28",
        "name": "Northwind Airflow",
        "available_sizes": ["twin_xl", "full", "queen", "king"],
        "price": 489,
        "firmness": 6,
        "support": 5,
        "cooling": 8,
        "motion_isolation": None,
        "materials": "Perforated cooling foam over a responsive coil unit",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 90,
        "warranty_years": 7,
    },
    {
        "sku_id": "S29",
        "name": "Granite Ridge Support",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king", "cal_king"],
        "price": 529,
        "firmness": 8,
        "support": 9,
        "cooling": 6,
        "motion_isolation": 5,
        "materials": "Firm zoned foam over reinforced pocketed coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 90,
        "warranty_years": 10,
    },
    {
        "sku_id": "S30",
        "name": "Meadow Cloud Plush",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 579,
        "firmness": 4,
        "support": 6,
        "cooling": None,
        "motion_isolation": 8,
        "materials": "Deep pressure-relief foam over pocketed coils",
        "contains_latex": None,
        "haul_away_CA_available": False,
        "trial_days": 90,
        "warranty_years": 8,
    },
    {
        "sku_id": "S31",
        "name": "Juniper Balanced Hybrid",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king"],
        "price": 599,
        "firmness": None,
        "support": 7,
        "cooling": 7,
        "motion_isolation": 7,
        "materials": "Neutral-feel foam with individually wrapped coils",
        "contains_latex": False,
        "haul_away_CA_available": None,
        "trial_days": 100,
        "warranty_years": 8,
    },
    {
        "sku_id": "S32",
        "name": "ClearSky Cooling Foam",
        "available_sizes": ["twin_xl", "full", "queen", "king", "cal_king"],
        "price": 649,
        "firmness": 6,
        "support": None,
        "cooling": 9,
        "motion_isolation": 6,
        "materials": "Open-cell cooling foam with an airflow-channel base",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": None,
    },
    {
        "sku_id": "S33",
        "name": "Greenhaven Latex Hybrid",
        "available_sizes": ["twin", "twin_xl", "queen", "king", "cal_king"],
        "price": 689,
        "firmness": 6,
        "support": 8,
        "cooling": 8,
        "motion_isolation": 6,
        "materials": "Ventilated latex comfort layer over pocketed coils",
        "contains_latex": True,
        "haul_away_CA_available": False,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S34",
        "name": "Riverbend Value Hybrid",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 729,
        "firmness": 6,
        "support": 7,
        "cooling": 7,
        "motion_isolation": None,
        "materials": "Adaptive foam over a five-zone pocketed coil base",
        "contains_latex": False,
        "haul_away_CA_available": None,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S35",
        "name": "Copperleaf Cool Support",
        "available_sizes": ["twin_xl", "full", "queen", "king", "cal_king"],
        "price": 749,
        "firmness": 7,
        "support": 8,
        "cooling": 9,
        "motion_isolation": 6,
        "materials": "Copper-infused cooling foam over zoned coils",
        "contains_latex": None,
        "haul_away_CA_available": True,
        "trial_days": 90,
        "warranty_years": 10,
    },
    {
        "sku_id": "S36",
        "name": "Hearthside Quiet Hybrid",
        "available_sizes": ["twin", "full", "queen", "king"],
        "price": 799,
        "firmness": 5,
        "support": 7,
        "cooling": 6,
        "motion_isolation": 9,
        "materials": "Motion-dampening memory foam with nested pocket coils",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 120,
        "warranty_years": 10,
    },
    {
        "sku_id": "S37",
        "name": "Seabreeze Responsive",
        "available_sizes": ["twin", "twin_xl", "full", "queen", "king", "cal_king"],
        "price": 829,
        "firmness": 6,
        "support": None,
        "cooling": 8,
        "motion_isolation": 5,
        "materials": "Breathable performance foam over responsive coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": None,
        "warranty_years": 10,
    },
    {
        "sku_id": "S38",
        "name": "Elm Street Pillow Top",
        "available_sizes": ["full", "queen", "king"],
        "price": 899,
        "firmness": None,
        "support": 7,
        "cooling": None,
        "motion_isolation": 7,
        "materials": "Fiber-and-foam pillow top over encased coils",
        "contains_latex": None,
        "haul_away_CA_available": None,
        "trial_days": 90,
        "warranty_years": 8,
    },
    {
        "sku_id": "S39",
        "name": "Stonebrook Firm Hybrid",
        "available_sizes": ["twin_xl", "queen", "king", "cal_king"],
        "price": 929,
        "firmness": 9,
        "support": 9,
        "cooling": 7,
        "motion_isolation": None,
        "materials": "Dense firm foam over a reinforced zoned-coil system",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": 100,
        "warranty_years": 12,
    },
    {
        "sku_id": "S40",
        "name": "Moonrise Memory Comfort",
        "available_sizes": ["twin", "full", "queen", "king", "cal_king"],
        "price": 979,
        "firmness": 4,
        "support": 6,
        "cooling": 6,
        "motion_isolation": 10,
        "materials": "Deep-contouring memory foam with a stable foam core",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 120,
        "warranty_years": 10,
    },
    {
        "sku_id": "S41",
        "name": "Blue Mesa Comfort Hybrid",
        "available_sizes": ["twin_xl", "full", "queen", "king", "cal_king"],
        "price": 1599,
        "firmness": 5,
        "support": 8,
        "cooling": None,
        "motion_isolation": 9,
        "materials": "Pressure-relief foam over zoned pocketed coils",
        "contains_latex": None,
        "haul_away_CA_available": True,
        "trial_days": 120,
        "warranty_years": 12,
    },
    {
        "sku_id": "S42",
        "name": "Glacier Point Performance",
        "available_sizes": ["queen", "king", "cal_king"],
        "price": 1749,
        "firmness": 7,
        "support": None,
        "cooling": 10,
        "motion_isolation": 7,
        "materials": "Phase-change cover, ventilated foam, and pocketed coils",
        "contains_latex": False,
        "haul_away_CA_available": None,
        "trial_days": 100,
        "warranty_years": 10,
    },
    {
        "sku_id": "S43",
        "name": "Ironwood Zoned Support",
        "available_sizes": ["twin_xl", "queen", "king", "cal_king"],
        "price": 1899,
        "firmness": 8,
        "support": 10,
        "cooling": 7,
        "motion_isolation": 6,
        "materials": "Multi-zone support foam over heavy-gauge pocketed coils",
        "contains_latex": False,
        "haul_away_CA_available": False,
        "trial_days": 120,
        "warranty_years": 15,
    },
    {
        "sku_id": "S44",
        "name": "Silvershore Pillow Hybrid",
        "available_sizes": ["full", "queen", "king"],
        "price": 1995,
        "firmness": 4,
        "support": 8,
        "cooling": 8,
        "motion_isolation": None,
        "materials": "Plush cooling pillow top over a dual-coil support system",
        "contains_latex": False,
        "haul_away_CA_available": True,
        "trial_days": None,
        "warranty_years": 12,
    },
    {
        "sku_id": "S45",
        "name": "Aurora Crest Balanced",
        "available_sizes": ["twin_xl", "full", "queen", "king", "cal_king"],
        "price": 2149,
        "firmness": None,
        "support": 9,
        "cooling": 9,
        "motion_isolation": 8,
        "materials": "Responsive cooling foams over reinforced microcoils and pocketed coils",
        "contains_latex": False,
        "haul_away_CA_available": None,
        "trial_days": 150,
        "warranty_years": 15,
    },
    {
        "sku_id": "S46",
        "name": "Alpine Air Latex Hybrid",
        "available_sizes": ["queen", "king", "cal_king"],
        "price": 2399,
        "firmness": 7,
        "support": 9,
        "cooling": None,
        "motion_isolation": 6,
        "materials": "Latex-like responsive comfort system over zoned coils; composition not fully documented",
        "contains_latex": None,
        "haul_away_CA_available": False,
        "trial_days": 120,
        "warranty_years": None,
    },
    {
        "sku_id": "S47",
        "name": "Canyon Reserve Latex",
        "available_sizes": ["twin_xl", "queen", "king", "cal_king"],
        "price": 2799,
        "firmness": 6,
        "support": 9,
        "cooling": 9,
        "motion_isolation": None,
        "materials": "Natural latex layers over a hand-tufted pocket-coil core",
        "contains_latex": True,
        "haul_away_CA_available": None,
        "trial_days": 180,
        "warranty_years": 20,
    },
    {
        "sku_id": "S48",
        "name": "Celestial Reserve Plush",
        "available_sizes": ["queen", "king", "cal_king"],
        "price": 3295,
        "firmness": 3,
        "support": None,
        "cooling": None,
        "motion_isolation": 9,
        "materials": "Hand-tufted wool blend, pressure-relief foam, and nested coils",
        "contains_latex": None,
        "haul_away_CA_available": True,
        "trial_days": 180,
        "warranty_years": None,
    },
]
