"""Precomputed, fixture-backed customer review evidence.

This module deliberately exposes a retrieval-shaped interface.  A future review
service can replace it without changing intent routing, ranking, or presentation.
Review records describe customer experience; they are never catalog facts.
"""

from copy import deepcopy
from typing import Any, Dict, Iterable, List, Optional


REVIEW_FIXTURE_SOURCE = "precomputed_customer_review_evidence_fixture_v1"

# Sentiment is intentionally qualitative.  Counts and ratings are demo fixture
# facts, not live marketplace values.
REVIEW_EVIDENCE: Dict[str, Dict[str, Any]] = {
    "S01": {"review_count": 1264, "average_rating": 4.5, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers frequently describe cooler sleep than on conventional foam beds."}, "motion_isolation": {"sentiment": "positive", "strength": "moderate", "summary": "Couples often report that ordinary movement stays fairly contained."}, "firmness": {"sentiment": "mixed", "strength": "moderate", "summary": "Many call the feel balanced, while some side sleepers find it firmer than expected."}}, "common_praise": ["cooler sleep", "balanced support"], "common_complaints": ["firmer feel than some side sleepers expected"]},
    "S02": {"review_count": 987, "average_rating": 4.6, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Cooler sleep is one of the most consistent positive themes."}, "motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Couples frequently mention very little movement transfer."}, "ease_of_movement": {"sentiment": "positive", "strength": "moderate", "summary": "Owners generally find it easy to change positions."}}, "common_praise": ["cool sleep", "limited motion transfer"], "common_complaints": ["heavy and awkward to rotate"]},
    "S03": {"review_count": 734, "average_rating": 4.3, "themes": {"contouring": {"sentiment": "positive", "strength": "moderate", "summary": "Many owners like the close contouring around shoulders and hips."}, "cooling": {"sentiment": "mixed", "strength": "moderate", "summary": "Some reviewers sleep comfortably, while others still notice foam warmth."}, "setup_odor": {"sentiment": "negative", "strength": "moderate", "summary": "A recurring complaint is an initial odor that takes a few days to fade."}}, "common_praise": ["pressure-relieving contour"], "common_complaints": ["initial odor", "warmer feel for some sleepers"]},
    "S04": {"review_count": 615, "average_rating": 4.4, "themes": {"cooling": {"sentiment": "positive", "strength": "moderate", "summary": "Breathability and a comfortably neutral temperature come up often."}, "firmness": {"sentiment": "mixed", "strength": "strong", "summary": "Owners disagree on the feel: some call it pleasantly soft, while others report too much give."}, "motion_isolation": {"sentiment": "positive", "strength": "moderate", "summary": "Partner movement is usually described as subdued."}}, "common_praise": ["comfortable surface feel", "good motion control"], "common_complaints": ["too much softness for some sleepers"]},
    "S05": {"review_count": 1108, "average_rating": 4.4, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers consistently praise its cool surface and reduced heat buildup."}, "firmness": {"sentiment": "mixed", "strength": "strong", "summary": "It is often experienced as distinctly firm, including by shoppers expecting medium-firm."}, "durability": {"sentiment": "positive", "strength": "moderate", "summary": "The support has held up well in the longer-use feedback represented here."}}, "common_praise": ["cool surface", "stable support"], "common_complaints": ["firmer than expected"]},
    "S06": {"review_count": 842, "average_rating": 4.4, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers frequently describe it as sleeping cooler than traditional memory foam."}, "motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Couples often mention limited movement transfer."}, "firmness": {"sentiment": "mixed", "strength": "moderate", "summary": "Most describe it as medium-firm, though some find it firmer than expected."}}, "common_praise": ["cooler sleep", "limited motion transfer"], "common_complaints": ["firmer than some shoppers expected"]},
    "S07": {"review_count": 529, "average_rating": 4.5, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Low partner disturbance is the clearest recurring positive theme."}, "contouring": {"sentiment": "mixed", "strength": "moderate", "summary": "Some enjoy the close hug, while others feel they sink in too deeply."}, "ease_of_movement": {"sentiment": "negative", "strength": "moderate", "summary": "A number of owners say repositioning takes more effort than they prefer."}}, "common_praise": ["very little partner disturbance"], "common_complaints": ["deep sinking feel", "harder repositioning"]},
    "S08": {"review_count": 921, "average_rating": 4.5, "themes": {"cooling": {"sentiment": "positive", "strength": "moderate", "summary": "Owners commonly describe a neutral-to-cool sleeping temperature."}, "ease_of_movement": {"sentiment": "positive", "strength": "strong", "summary": "The responsive feel makes changing positions easy for many sleepers."}, "durability": {"sentiment": "mixed", "strength": "weak", "summary": "Most durability feedback is positive, with a smaller recurring concern about edge softening."}}, "common_praise": ["responsive feel", "easy movement"], "common_complaints": ["edge softening in some longer-use feedback"]},
    "S09": {"review_count": 688, "average_rating": 4.3, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers often praise how well it limits movement transfer."}, "contouring": {"sentiment": "positive", "strength": "moderate", "summary": "The pressure-relieving hug is popular with side sleepers."}, "cooling": {"sentiment": "mixed", "strength": "moderate", "summary": "Temperature feedback is divided, especially among people who already sleep hot."}}, "common_praise": ["pressure relief", "limited motion transfer"], "common_complaints": ["heat buildup for some hot sleepers"]},
    "S10": {"review_count": 473, "average_rating": 4.2, "themes": {"value": {"sentiment": "positive", "strength": "strong", "summary": "Many reviewers consider the comfort good for the price."}, "cooling": {"sentiment": "positive", "strength": "moderate", "summary": "A breathable, not overly warm feel is mentioned regularly."}, "durability": {"sentiment": "negative", "strength": "moderate", "summary": "A recurring concern is early softening in heavily used areas."}}, "common_praise": ["good comfort for the price"], "common_complaints": ["early softening"]},
    "S11": {"review_count": 556, "average_rating": 4.3, "themes": {"firmness": {"sentiment": "positive", "strength": "moderate", "summary": "The balanced medium-firm feel works well for many reviewers."}, "motion_isolation": {"sentiment": "mixed", "strength": "moderate", "summary": "Most couples are satisfied, though lighter sleepers sometimes notice movement."}, "setup_odor": {"sentiment": "negative", "strength": "weak", "summary": "Some owners mention a short-lived new-mattress odor."}}, "common_praise": ["balanced feel"], "common_complaints": ["some partner movement", "brief setup odor"]},
    "S12": {"review_count": 804, "average_rating": 4.5, "themes": {"firmness": {"sentiment": "mixed", "strength": "strong", "summary": "Back sleepers often like the firm support, but some side sleepers call it too hard."}, "ease_of_movement": {"sentiment": "positive", "strength": "strong", "summary": "Its buoyant surface is frequently described as easy to move on."}, "cooling": {"sentiment": "positive", "strength": "moderate", "summary": "Most represented feedback describes comfortable temperature control."}}, "common_praise": ["strong lumbar support", "easy movement"], "common_complaints": ["too firm for some side sleepers"]},
    "S13": {"review_count": 642, "average_rating": 4.4, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Cooler sleep comes up repeatedly in the positive feedback."}, "motion_isolation": {"sentiment": "positive", "strength": "moderate", "summary": "Most couples report manageable movement transfer."}, "setup_odor": {"sentiment": "mixed", "strength": "weak", "summary": "A few reviewers mention an odor after unboxing, usually described as temporary."}}, "common_praise": ["cooler sleep", "comfortable cushioning"], "common_complaints": ["temporary unboxing odor"]},
    "S14": {"review_count": 1351, "average_rating": 4.2, "themes": {"value": {"sentiment": "positive", "strength": "strong", "summary": "Affordability and solid everyday comfort are the dominant positive themes."}, "cooling": {"sentiment": "mixed", "strength": "moderate", "summary": "Some sleepers find the temperature comfortable, while hot sleepers more often report warmth."}, "durability": {"sentiment": "negative", "strength": "moderate", "summary": "Longer-use feedback includes recurring concerns about impressions and softening."}}, "common_praise": ["strong value", "comfortable initial feel"], "common_complaints": ["body impressions", "warmth for hot sleepers"]},
    "S15": {"review_count": 769, "average_rating": 4.6, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "The strongest review theme is sustained cooler sleep."}, "motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Couples commonly report little disruption from movement."}, "firmness": {"sentiment": "mixed", "strength": "moderate", "summary": "Most call it medium-firm, with a smaller group finding the surface stiff at first."}}, "common_praise": ["sustained cooling", "low partner disturbance"], "common_complaints": ["stiff initial feel"]},
    "S16": {"review_count": 498, "average_rating": 4.3, "themes": {"contouring": {"sentiment": "positive", "strength": "strong", "summary": "Owners often praise the gentle cushioning and pressure relief."}, "firmness": {"sentiment": "mixed", "strength": "moderate", "summary": "Many like the softer feel, while some stomach sleepers want more firmness."}, "motion_isolation": {"sentiment": "positive", "strength": "moderate", "summary": "Movement from a partner is generally described as well controlled."}}, "common_praise": ["gentle pressure relief"], "common_complaints": ["not firm enough for some stomach sleepers"]},
    "S17": {"review_count": 713, "average_rating": 4.5, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Couples consistently mention minimal disturbance from movement."}, "cooling": {"sentiment": "positive", "strength": "moderate", "summary": "Most reviewers describe steady, comfortable temperature regulation."}, "firmness": {"sentiment": "mixed", "strength": "weak", "summary": "The feel is usually called medium-firm, though perceptions vary by body type."}}, "common_praise": ["minimal movement disturbance", "comfortable temperature"], "common_complaints": ["heavier than expected"]},
    "S18": {"review_count": 581, "average_rating": 4.2, "themes": {"firmness": {"sentiment": "positive", "strength": "moderate", "summary": "Reviewers often describe a familiar, balanced hybrid feel."}, "motion_isolation": {"sentiment": "positive", "strength": "moderate", "summary": "Motion control is generally well received by couples."}, "durability": {"sentiment": "mixed", "strength": "moderate", "summary": "The center support gets positive comments, but some report softer edges over time."}}, "common_praise": ["balanced hybrid feel"], "common_complaints": ["edges softening over time"]},
    "S19": {"review_count": 444, "average_rating": 4.3, "themes": {"cooling": {"sentiment": "positive", "strength": "moderate", "summary": "Reviewers often mention less heat buildup than expected at this price."}, "ease_of_movement": {"sentiment": "positive", "strength": "moderate", "summary": "The springy response helps many sleepers turn easily."}, "setup_odor": {"sentiment": "negative", "strength": "moderate", "summary": "Initial odor is a recurring setup complaint."}}, "common_praise": ["breathable feel", "easy repositioning"], "common_complaints": ["initial odor"]},
    "S20": {"review_count": 1006, "average_rating": 4.0, "themes": {"value": {"sentiment": "positive", "strength": "strong", "summary": "Low price and straightforward comfort drive most of the praise."}, "cooling": {"sentiment": "mixed", "strength": "strong", "summary": "Temperature feedback is split, with hot sleepers frequently reporting warmth."}, "durability": {"sentiment": "negative", "strength": "strong", "summary": "Sagging and loss of support are recurring longer-use concerns."}}, "common_praise": ["accessible price"], "common_complaints": ["warmth for hot sleepers", "loss of support over time"]},
}


def get_review_record(sku_id: str) -> Optional[Dict[str, Any]]:
    record = REVIEW_EVIDENCE.get(sku_id)
    return deepcopy(record) if record is not None else None


def review_slice(sku_ids: Iterable[str], topic: Optional[str]) -> Dict[str, Any]:
    """Return only evidence relevant to one response."""
    records: List[Dict[str, Any]] = []
    unknown_topics: List[Dict[str, str]] = []
    for sku_id in sku_ids:
        record = REVIEW_EVIDENCE.get(sku_id)
        if record is None:
            continue
        item: Dict[str, Any] = {"sku_id": sku_id}
        if topic in (None, "general"):
            item.update(deepcopy(record))
        elif topic == "praise":
            item["common_praise"] = deepcopy(record.get("common_praise", []))
        elif topic == "complaints":
            item["common_complaints"] = deepcopy(record.get("common_complaints", []))
        elif topic in record.get("themes", {}):
            item["themes"] = {topic: deepcopy(record["themes"][topic])}
        else:
            unknown_topics.append({"sku_id": sku_id, "topic": str(topic or "unknown")})
        records.append(item)
    return {
        "authoritative_source": REVIEW_FIXTURE_SOURCE,
        "requested_topic": topic or "general",
        "records": records,
        "unknown_topics": unknown_topics,
    }
