"""Precomputed, fixture-backed customer review evidence.

This module deliberately exposes a retrieval-shaped interface.  A future review
service can replace it without changing intent routing, ranking, or presentation.
Review records describe customer experience; they are never catalog facts.
"""

from copy import deepcopy
from typing import Any, Dict, Iterable, List, Optional


REVIEW_FIXTURE_VERSION = "reviews_v2"
REVIEW_FIXTURE_SOURCE = "precomputed_customer_review_evidence_fixture_v2"

# Sentiment is intentionally qualitative.  Counts and ratings are demo fixture
# facts, not live marketplace values.
REVIEW_EVIDENCE: Dict[str, Dict[str, Any]] = {
    "S01": {"review_count": 1264, "average_rating": 4.5, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers frequently describe cooler sleep than on conventional foam beds."}, "motion_isolation": {"sentiment": "positive", "strength": "moderate", "summary": "Couples often report that ordinary movement stays fairly contained."}, "firmness": {"sentiment": "mixed", "strength": "moderate", "summary": "Many call the feel balanced, while some side sleepers find it firmer than expected."}}, "common_praise": ["cooler sleep", "balanced support"], "common_complaints": ["firmer feel than some side sleepers expected"]},
    "S02": {"review_count": 987, "average_rating": 4.6, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Cooler sleep is one of the most consistent positive themes."}, "motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Couples frequently mention very little movement transfer."}, "ease_of_movement": {"sentiment": "positive", "strength": "moderate", "summary": "Owners generally find it easy to change positions."}}, "common_praise": ["cool sleep", "limited motion transfer"], "common_complaints": ["heavy and awkward to rotate"]},
    "S03": {"review_count": 734, "average_rating": 4.3, "themes": {"contouring": {"sentiment": "positive", "strength": "moderate", "summary": "Many owners like the close contouring around shoulders and hips."}, "cooling": {"sentiment": "mixed", "strength": "moderate", "summary": "Some reviewers sleep comfortably, while others still notice foam warmth."}, "setup_odor": {"sentiment": "negative", "strength": "moderate", "summary": "A recurring complaint is an initial odor that takes a few days to fade."}}, "common_praise": ["pressure-relieving contour"], "common_complaints": ["initial odor", "warmer feel for some sleepers"]},
    "S04": {"review_count": 615, "average_rating": 4.4, "themes": {"cooling": {"sentiment": "positive", "strength": "moderate", "summary": "Breathability and a comfortably neutral temperature come up often."}, "firmness": {"sentiment": "mixed", "strength": "strong", "summary": "Owners disagree on the feel: some call it pleasantly soft, while others report too much give."}, "motion_isolation": {"sentiment": "positive", "strength": "moderate", "summary": "Partner movement is usually described as subdued."}}, "common_praise": ["comfortable surface feel", "good motion control"], "common_complaints": ["too much softness for some sleepers"]},
    "S05": {"review_count": 1108, "average_rating": 4.4, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers consistently praise its cool surface and reduced heat buildup."}, "firmness": {"sentiment": "mixed", "strength": "strong", "summary": "It is often experienced as distinctly firm, including by shoppers expecting medium-firm."}, "durability": {"sentiment": "positive", "strength": "moderate", "summary": "The support has held up well in the longer-use feedback represented here."}}, "common_praise": ["cool surface", "stable support"], "common_complaints": ["firmer than expected"]},
    "S06": {"review_count": 842, "average_rating": 4.4, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers frequently describe it as sleeping cooler than traditional memory foam."}, "motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Couples often mention limited movement transfer."}, "firmness": {"sentiment": "mixed", "strength": "moderate", "summary": "Most describe it as medium-firm, though some find it firmer than expected."}}, "common_praise": ["cooler sleep", "limited motion transfer"], "common_complaints": ["firmer than some shoppers expected"]},
    "S07": {"review_count": 529, "average_rating": 4.5, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Low partner disturbance is the clearest recurring positive theme."}, "contouring": {"sentiment": "mixed", "strength": "moderate", "summary": "Some enjoy the close hug, while others feel they sink in too deeply."}, "ease_of_movement": {"sentiment": "negative", "strength": "moderate", "summary": "A number of owners say repositioning takes more effort than they prefer."}}, "common_praise": ["very little partner disturbance"], "common_complaints": ["deep sinking feel", "harder repositioning"]},
    "S08": {"review_count": 921, "average_rating": 4.5, "themes": {"cooling": {"sentiment": "positive", "strength": "moderate", "summary": "Owners commonly describe a neutral-to-cool sleeping temperature."}, "ease_of_movement": {"sentiment": "positive", "strength": "strong", "summary": "The responsive feel makes changing positions easy for many sleepers."}, "durability": {"sentiment": "mixed", "strength": "weak", "summary": "Most durability feedback is positive, with a smaller recurring concern about edge softening."}}, "common_praise": ["responsive feel", "easy movement"], "common_complaints": ["edge softening in some longer-use feedback"]},
    "S09": {"review_count": 688, "average_rating": 4.3, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers often praise how well it limits movement transfer."}, "contouring": {"sentiment": "positive", "strength": "moderate", "summary": "The pressure-relieving hug is popular with side sleepers."}, "cooling": {"sentiment": "mixed", "strength": "moderate", "summary": "Temperature feedback is divided, especially among people who already sleep hot."}}, "common_praise": ["pressure relief", "limited motion transfer"], "common_complaints": ["heat buildup for some hot sleepers"]},
    "S10": {"review_count": 473, "average_rating": 4.2, "themes": {"value": {"sentiment": "positive", "strength": "strong", "summary": "Many reviewers consider the comfort good for the price."}, "cooling": {"sentiment": "positive", "strength": "moderate", "summary": "A breathable, not overly warm feel is mentioned regularly."}, "durability": {"sentiment": "negative", "strength": "moderate", "summary": "A recurring concern is early softening in heavily used areas."}}, "common_praise": ["good comfort for the price"], "common_complaints": ["early softening"]},
    "S11": {"review_count": 556, "average_rating": 4.3, "themes": {"firmness": {"sentiment": "positive", "strength": "moderate", "summary": "The balanced medium-firm feel works well for many reviewers."}, "motion_isolation": {"sentiment": "mixed", "strength": "moderate", "summary": "Most couples are satisfied, though lighter sleepers sometimes notice movement."}, "setup_odor": {"sentiment": "negative", "strength": "weak", "summary": "Some owners mention a short-lived new-mattress odor."}}, "common_praise": ["balanced feel"], "common_complaints": ["some partner movement", "brief setup odor"]},
    "S12": {"review_count": 804, "average_rating": 4.5, "themes": {"firmness": {"sentiment": "mixed", "strength": "strong", "summary": "Back sleepers often like the firm support, but some side sleepers call it too hard."}, "ease_of_movement": {"sentiment": "positive", "strength": "strong", "summary": "Its buoyant surface is frequently described as easy to move on."}, "cooling": {"sentiment": "positive", "strength": "moderate", "summary": "Most represented feedback describes comfortable temperature control."}}, "common_praise": ["strong lumbar support", "easy movement"], "common_complaints": ["too firm for some side sleepers"]},
    "S13": {"review_count": 642, "average_rating": 4.4, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Cooler sleep comes up repeatedly in the positive feedback."}, "motion_isolation": {"sentiment": "positive", "strength": "moderate", "summary": "Most couples report manageable movement transfer."}, "setup_odor": {"sentiment": "mixed", "strength": "weak", "summary": "A few reviewers mention an odor after unboxing, usually described as temporary."}}, "common_praise": ["cooler sleep", "comfortable cushioning"], "common_complaints": ["temporary unboxing odor"]},
    "S14": {"review_count": 1351, "average_rating": 4.2, "themes": {"value": {"sentiment": "positive", "strength": "strong", "summary": "Affordability and solid everyday comfort are the dominant positive themes."}, "cooling": {"sentiment": "mixed", "strength": "moderate", "summary": "Some sleepers find the temperature comfortable, while hot sleepers more often report warmth."}, "durability": {"sentiment": "negative", "strength": "moderate", "summary": "Longer-use feedback includes recurring concerns about impressions and softening."}}, "common_praise": ["strong value", "comfortable initial feel"], "common_complaints": ["body impressions", "warmth for hot sleepers"]},
    "S15": {"review_count": 769, "average_rating": 4.6, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "The strongest review theme is sustained cooler sleep."}, "motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Couples commonly report little disruption from movement."}, "firmness": {"sentiment": "mixed", "strength": "moderate", "summary": "Most call it medium-firm, with a smaller group finding the surface stiff at first."}}, "common_praise": ["sustained cooling", "low partner disturbance"], "common_complaints": ["stiff initial feel"]},
    "S16": {"review_count": 498, "average_rating": 4.3, "themes": {"contouring": {"sentiment": "positive", "strength": "strong", "summary": "Owners often praise the gentle cushioning and pressure relief."}, "firmness": {"sentiment": "mixed", "strength": "moderate", "summary": "Many like the softer feel, while some stomach sleepers want more firmness."}, "motion_isolation": {"sentiment": "positive", "strength": "moderate", "summary": "Movement from a partner is generally described as well controlled."}}, "common_praise": ["gentle pressure relief"], "common_complaints": ["not firm enough for some stomach sleepers"]},
    "S17": {"review_count": 713, "average_rating": 4.5, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Couples consistently mention minimal disturbance from movement."}, "cooling": {"sentiment": "positive", "strength": "moderate", "summary": "Most reviewers describe steady, comfortable temperature regulation."}, "firmness": {"sentiment": "mixed", "strength": "weak", "summary": "The feel is usually called medium-firm, though perceptions vary by body type."}}, "common_praise": ["minimal movement disturbance", "comfortable temperature"], "common_complaints": ["heavier than expected"]},
    "S18": {"review_count": 581, "average_rating": 4.2, "themes": {"firmness": {"sentiment": "positive", "strength": "moderate", "summary": "Reviewers often describe a familiar, balanced hybrid feel."}, "motion_isolation": {"sentiment": "positive", "strength": "moderate", "summary": "Motion control is generally well received by couples."}, "durability": {"sentiment": "mixed", "strength": "moderate", "summary": "The center support gets positive comments, but some report softer edges over time."}}, "common_praise": ["balanced hybrid feel"], "common_complaints": ["edges softening over time"]},
    "S19": {"review_count": 444, "average_rating": 4.3, "themes": {"cooling": {"sentiment": "positive", "strength": "moderate", "summary": "Reviewers often mention less heat buildup than expected at this price."}, "ease_of_movement": {"sentiment": "positive", "strength": "moderate", "summary": "The springy response helps many sleepers turn easily."}, "setup_odor": {"sentiment": "negative", "strength": "moderate", "summary": "Initial odor is a recurring setup complaint."}}, "common_praise": ["breathable feel", "easy repositioning"], "common_complaints": ["initial odor"]},
    "S20": {"review_count": 1006, "average_rating": 4.0, "themes": {"value": {"sentiment": "positive", "strength": "strong", "summary": "Low price and straightforward comfort drive most of the praise."}, "cooling": {"sentiment": "mixed", "strength": "strong", "summary": "Temperature feedback is split, with hot sleepers frequently reporting warmth."}, "durability": {"sentiment": "negative", "strength": "strong", "summary": "Sagging and loss of support are recurring longer-use concerns."}}, "common_praise": ["accessible price"], "common_complaints": ["warmth for hot sleepers", "loss of support over time"]},
    "S21": {"review_count": 1642, "average_rating": 4.1, "themes": {"value": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers often call it a practical guest-room or first-mattress value."}, "firmness": {"sentiment": "mixed", "strength": "moderate", "summary": "The straightforward medium-firm feel works for many, though the surface feels thin to some."}}, "common_praise": ["accessible price", "simple setup"], "common_complaints": ["thin comfort layer"]},
    "S22": {"review_count": 1198, "average_rating": 4.3, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Couples repeatedly praise how little ordinary movement carries across the bed."}, "contouring": {"sentiment": "mixed", "strength": "moderate", "summary": "Some like the close foam hug, while others find repositioning slow."}}, "common_praise": ["very little partner disturbance"], "common_complaints": ["slow response"]},
    "S23": {"review_count": 674, "average_rating": 4.2, "themes": {"firmness": {"sentiment": "positive", "strength": "strong", "summary": "Back and stomach sleepers commonly praise the distinctly firm surface."}, "cooling": {"sentiment": "mixed", "strength": "weak", "summary": "Temperature comments are limited and divided."}}, "common_praise": ["stable firm feel"], "common_complaints": ["too hard for some side sleepers"]},
    "S24": {"review_count": 382, "average_rating": 4.0, "themes": {"contouring": {"sentiment": "positive", "strength": "moderate", "summary": "The soft cushioning gets favorable comments from lighter side sleepers."}}, "common_praise": ["soft pressure relief"]},
    "S25": {"review_count": 913, "average_rating": 3.9, "themes": {"cooling": {"sentiment": "positive", "strength": "moderate", "summary": "The open coil design is commonly described as breathable."}, "motion_isolation": {"sentiment": "negative", "strength": "strong", "summary": "Partner movement and bounce are frequent complaints."}}, "common_praise": ["breathable feel", "easy movement"], "common_complaints": ["noticeable partner movement"]},
    "S26": {"review_count": 247, "average_rating": 4.1, "themes": {"value": {"sentiment": "positive", "strength": "moderate", "summary": "Owners generally consider it comfortable for the price."}}, "common_complaints": ["limited edge stability"]},
    "S27": {"review_count": 1086, "average_rating": 4.5, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Low movement transfer is the clearest and most consistent review theme."}, "cooling": {"sentiment": "mixed", "strength": "moderate", "summary": "Some sleep comfortably, while hot sleepers more often notice warmth."}}, "common_praise": ["quiet surface", "limited motion transfer"], "common_complaints": ["warmth for some sleepers"]},
    "S28": {"review_count": 735, "average_rating": 4.2, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers regularly mention good airflow and a cooler surface."}, "durability": {"sentiment": "mixed", "strength": "weak", "summary": "Long-term feedback is still sparse, with a few reports of edge softening."}}, "common_praise": ["cooler sleep"], "common_complaints": ["edge softening"]},
    "S29": {"review_count": 821, "average_rating": 4.4, "themes": {"firmness": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers seeking firm support frequently say it feels stable and level."}, "ease_of_movement": {"sentiment": "positive", "strength": "moderate", "summary": "The buoyant coil response makes turning easy for many sleepers."}}, "common_praise": ["strong support", "easy repositioning"], "common_complaints": ["too firm for some"]},
    "S30": {"review_count": 466, "average_rating": 4.2, "themes": {"contouring": {"sentiment": "positive", "strength": "strong", "summary": "Side sleepers often praise the deep cushioning around shoulders and hips."}, "ease_of_movement": {"sentiment": "negative", "strength": "moderate", "summary": "Some owners feel held in place by the softer foam."}}, "common_praise": ["pressure relief"], "common_complaints": ["harder repositioning"]},
    "S31": {"review_count": 589, "average_rating": 4.3, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "moderate", "summary": "Most couples describe movement transfer as well controlled."}}, "common_praise": ["balanced everyday comfort"]},
    "S32": {"review_count": 954, "average_rating": 4.4, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Reduced heat buildup is the most repeated positive theme."}, "contouring": {"sentiment": "mixed", "strength": "moderate", "summary": "The lighter contour works for some sleepers but feels shallow to others."}}, "common_praise": ["cool surface"], "common_complaints": ["less cushioning than expected"]},
    "S33": {"review_count": 438, "average_rating": 4.5, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Owners commonly describe the ventilated latex layer as breathable."}, "ease_of_movement": {"sentiment": "positive", "strength": "strong", "summary": "The springy surface makes position changes easy."}}, "common_praise": ["buoyant feel", "breathability"], "common_complaints": ["more bounce than some couples prefer"]},
    "S34": {"review_count": 512, "average_rating": 4.3, "themes": {"value": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers like the balanced hybrid feel at its price."}, "firmness": {"sentiment": "mixed", "strength": "weak", "summary": "Feel descriptions vary from medium to medium-firm."}}, "common_praise": ["balanced value"]},
    "S35": {"review_count": 689, "average_rating": 4.4, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Cooler sleep and quick heat dissipation appear often in represented feedback."}, "firmness": {"sentiment": "mixed", "strength": "moderate", "summary": "Many like the supportive feel, though some find the top firmer than expected."}}, "common_praise": ["cool sleep", "stable feel"], "common_complaints": ["firm initial surface"]},
    "S36": {"review_count": 1037, "average_rating": 4.6, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Couples consistently report very little disturbance from ordinary movement."}, "contouring": {"sentiment": "positive", "strength": "moderate", "summary": "The foam provides noticeable cushioning without an especially deep sink."}}, "common_praise": ["excellent motion control"], "common_complaints": ["heavy to rotate"]},
    "S37": {"review_count": 371, "average_rating": 4.1, "themes": {"cooling": {"sentiment": "positive", "strength": "moderate", "summary": "The breathable surface receives favorable temperature comments."}, "motion_isolation": {"sentiment": "negative", "strength": "moderate", "summary": "Light sleepers sometimes notice a partner changing positions."}}, "common_praise": ["responsive, airy feel"], "common_complaints": ["noticeable bounce"]},
    "S38": {"review_count": 228, "average_rating": 4.0, "themes": {"contouring": {"sentiment": "mixed", "strength": "moderate", "summary": "Some enjoy the cushioned pillow top, while others report uneven softness."}}, "common_complaints": ["softness varies by sleeping position"]},
    "S39": {"review_count": 607, "average_rating": 4.5, "themes": {"firmness": {"sentiment": "positive", "strength": "strong", "summary": "People shopping specifically for a very firm bed often praise its stable feel."}, "support": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers regularly mention a supported, level sleeping position."}}, "common_praise": ["very firm support"], "common_complaints": ["little surface cushioning"]},
    "S40": {"review_count": 778, "average_rating": 4.5, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Minimal partner disturbance is the dominant positive theme."}, "contouring": {"sentiment": "mixed", "strength": "strong", "summary": "The deep hug relieves pressure for some but feels restrictive to others."}}, "common_praise": ["exceptional motion isolation", "deep pressure relief"], "common_complaints": ["slow repositioning"]},
    "S41": {"review_count": 326, "average_rating": 4.4, "themes": {"motion_isolation": {"sentiment": "positive", "strength": "strong", "summary": "Couples often praise the calm, low-disturbance surface."}, "contouring": {"sentiment": "positive", "strength": "moderate", "summary": "Reviewers like the cushioning through shoulders and hips."}}, "common_praise": ["quiet sleep", "pressure relief"]},
    "S42": {"review_count": 845, "average_rating": 4.6, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "The cool-touch surface and limited overnight heat buildup are widely praised."}, "firmness": {"sentiment": "mixed", "strength": "moderate", "summary": "It feels supportive to many, but some side sleepers want more give."}}, "common_praise": ["excellent temperature control"], "common_complaints": ["too firm for some side sleepers"]},
    "S43": {"review_count": 493, "average_rating": 4.5, "themes": {"support": {"sentiment": "positive", "strength": "strong", "summary": "Stable lumbar and edge support are recurring positive themes."}, "motion_isolation": {"sentiment": "mixed", "strength": "moderate", "summary": "The sturdy coil system feels responsive, with some movement transfer reported."}}, "common_praise": ["strong zoned support"], "common_complaints": ["some partner movement"]},
    "S44": {"review_count": 284, "average_rating": 4.3, "themes": {"contouring": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers commonly praise the plush pressure relief."}, "cooling": {"sentiment": "positive", "strength": "moderate", "summary": "Most represented temperature feedback is favorable."}}, "common_praise": ["plush cushioning"], "common_complaints": ["tall profile complicates fitted sheets"]},
    "S45": {"review_count": 417, "average_rating": 4.7, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Owners frequently describe steady temperature control through the night."}, "support": {"sentiment": "positive", "strength": "strong", "summary": "The reinforced construction receives strong stability feedback."}}, "common_praise": ["balanced performance", "stable support"], "common_complaints": ["heavy construction"]},
    "S46": {"review_count": 96, "average_rating": 4.2, "themes": {"ease_of_movement": {"sentiment": "positive", "strength": "moderate", "summary": "The responsive surface is generally easy to move across."}}, "common_praise": ["buoyant response"]},
    "S47": {"review_count": 173, "average_rating": 4.6, "themes": {"cooling": {"sentiment": "positive", "strength": "strong", "summary": "Breathability is a consistent positive theme in the smaller review sample."}, "ease_of_movement": {"sentiment": "positive", "strength": "strong", "summary": "Reviewers like the quick, springy response."}}, "common_praise": ["breathable latex feel", "easy movement"], "common_complaints": ["noticeable bounce"]},
    "S48": {"review_count": 37, "average_rating": 4.4, "themes": {"contouring": {"sentiment": "positive", "strength": "moderate", "summary": "The limited feedback represented here praises the plush surface cushioning."}}, "common_praise": ["luxurious plush feel"]},
}


def get_review_record(sku_id: str) -> Optional[Dict[str, Any]]:
    record = REVIEW_EVIDENCE.get(sku_id)
    return deepcopy(record) if record is not None else None


def review_slice(sku_ids: Iterable[str], topic: Optional[str]) -> Dict[str, Any]:
    """Return only evidence relevant to one response."""
    records: List[Dict[str, Any]] = []
    unknown_topics: List[Dict[str, str]] = []
    for sku_id in sku_ids:
        record = REVIEW_EVIDENCE.get(sku_id)
        if record is None:
            continue
        item: Dict[str, Any] = {"sku_id": sku_id}
        if topic in (None, "general"):
            item.update(deepcopy(record))
        elif topic == "praise":
            item["common_praise"] = deepcopy(record.get("common_praise", []))
        elif topic == "complaints":
            item["common_complaints"] = deepcopy(record.get("common_complaints", []))
        elif topic in record.get("themes", {}):
            item["themes"] = {topic: deepcopy(record["themes"][topic])}
        else:
            unknown_topics.append({"sku_id": sku_id, "topic": str(topic or "unknown")})
        records.append(item)
    return {
        "authoritative_source": REVIEW_FIXTURE_SOURCE,
        "requested_topic": topic or "general",
        "records": records,
        "unknown_topics": unknown_topics,
    }
